build-game:
   stage: build
   script:
      - make cardGame
   artifacts:
      paths:
         - cardGame

build-test:
   stage: build
   script:
      - make testGame
   artifacts:
      paths:
         - testGame

test-game:
   stage: test
   script:
      - testGame
      - make memcheck-test
      - make static
   artifacts:
      paths:
         - ValgrindOutput.xml
         - CppCheckResults.xml

pages:
   stage: deploy
   dependencies:
      - testGame
   script:
      - make coverage
   artifacts:
      paths:
         - coverage
      expire_in: 30 days
   only:
      - master

pages:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 30 days
   only:
      - master

